### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by samupozzo** [Todo56/ShopUI#7]
Can you add cmd's for buying an item? (Es. 1 of paper and the console runs a command like setgroup {player} group)

**Comment by Todo56** [comment]
Like /buy or something like that? Or like permissions for each item?

**Comment by samupozzo** [comment]
No, like if I buy an item the console will run a command for me, like to buy a rank or a cosmetic on the shop

**Comment by Todo56** [comment]
This feature might be added soon if I find an efficient and simple way to do so. Thanks for the suggestion!

**Comment by BroCrows** [comment]
Ohh yeah please add

**Comment by Todo56** [comment]
I've added the command feature, is still not fully tested so if it has any bug please report it, and if you have any other suggestion please dm me in discord (Todo56#0001)
